dataset: 'CIFAR100'
data_root: 'data'
model: 'resnest26d'
pretrained: False
batch_size: 128
epochs: 150
num_workers: 8
lr: 0.1
optimizer: 'SAM'
scheduler: 'StepLR'
weight_decay: 0.0005
early_stopping_patience: 15
grad_clip: 1.0
batch_size_schedule: [{'epoch':75, 'batch_size':256}, {'epoch':120, 'batch_size':512}]
device: 'cuda'
wandb: true
seed: 42