dataset: 'CIFAR10'
data_root: 'data'
model: 'resnet18'
pretrained: False
batch_size: 128
epochs: 100
num_workers: 8
lr: 0.1
optimizer: 'SGD'
scheduler: 'StepLR'
weight_decay: 0.0005
early_stopping_patience: 10
grad_clip: 0.5
batch_size_schedule: [{'epoch':80, 'batch_size':256}]
device: 'cuda'
wandb: true
seed: 42