dataset: 'CIFAR100'
data_root: 'data'
model: 'resnet18'
pretrained: True
batch_size: 128
epochs: 50
num_workers: 8
lr: 0.0001
optimizer: 'AdamW'
scheduler: 'ReduceLROnPlateau'
weight_decay: 0.0001
early_stopping_patience: 8
grad_clip: False
batch_size_schedule: False
device: 'cuda'
wandb: true
seed: 42