dataset: 'OxfordIIITPet'
data_root: 'data'
model: 'resnet50'
pretrained: True
batch_size: 32
epochs: 25  
num_workers: 8
lr: 0.00005
optimizer: 'AdamW'
scheduler: 'ReduceLROnPlateau'
weight_decay: 0.0001
early_stopping_patience: 5
grad_clip: 1.0
batch_size_schedule: False
device: 'cuda'
wandb: true
seed: 42