dataset: 'CIFAR100'
data_root: 'data'
model: 'resnet18'
pretrained: False
batch_size: 128
epochs: 100
num_workers: 8
lr: 0.1
optimizer: 'SGD'
scheduler: 'StepLR'
weight_decay: 0.0001
early_stopping_patience: 10
grad_clip: False
batch_size_schedule: False
device: 'cuda'
wandb: true
seed: 42