dataset: 'CIFAR100'
data_root: 'data'
model: 'MLP'
pretrained: False
batch_size: 128
epochs: 50
num_workers: 8
lr: 0.003
optimizer: 'AdamW'
scheduler: 'StepLR'
weight_decay: 0.0001
early_stopping_patience: 8
grad_clip: False
batch_size_schedule: False
device: 'cuda'
wandb: true
seed: 42