dataset: 'MNIST'
data_root: 'data'
model: 'MLP'
pretrained: False
batch_size: 64
epochs: 15
num_workers: 4
lr: 0.005
optimizer: 'Adam'
scheduler: 'StepLR'
weight_decay: 0.00001
early_stopping_patience: 5
grad_clip: False
batch_size_schedule: False
device: 'cuda'
wandb: True
seed: 42